CREATE TABLE IF NOT EXISTS app_info (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT OR REPLACE INTO app_info (key, value) VALUES ('health', 'ok');