name: Deploy API (Worker)

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install Wrangler globally (pin exact version for reproducibility)
      - name: Setup Node and Wrangler
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install Wrangler
        run: npm i -g wrangler@3.80.2

      # Publish from /api with explicit account and verbose logs
      - name: Publish Worker
        working-directory: api
        env:
          CLOUDFLARE_API_TOKEN: \${{ secrets.CF_API_TOKEN }}   # Wrangler reads this env var
        run: |
          wrangler --version
          wrangler publish `
            --env=\${{ github.ref_name == 'main' && 'prod' || 'dev' }} `
            --account-id \${{ secrets.CF_ACCOUNT_ID }} `
            --verbose